services:
  - type: web
    name: tensor2tensor-app
    env: python
    buildCommand: >
      apt-get update && 
      apt-get install -y build-essential python3-dev &&
      pip install --upgrade pip &&
      pip install wheel setuptools &&
      pip install -r requirements.txt
    startCommand: gunicorn app:app --log-file=-
    healthCheckPath: /health
    healthCheckTimeout: 120
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: MNIST_PRELOAD_DATA
        value: 1
      - key: PORT
        sync: true